;==========================================================
; Polybar Config - Clean & Minimalist Nordic Style
;==========================================================

[colors]
blue-gray = #5f6f7f 
background = #242424
background-alt = #2196F3
foreground = #FFFFFF
primary = #64B5F6
secondary = #42A5F5
alert = #EF5350
disabled = #B0BEC5
border-clr = #00FFFFFF

[bar/bar]
width = 100%
height = 30
radius = 10
background = ${colors.background}
foreground = ${colors.foreground}
padding-left = 2 
padding-right = 2
module-margin = 1
font-0 = JetBrains Mono:size=12;2
font-1 = Font Awesome 7 Free Solid:size=12;2
modules-left = xworkspaces 
modules-center = xwindow
modules-right = pulseaudio memory cpu powermenu wlan battery date
enable-ipc = true
monitor = ${env:MONITOR}

;;;;;;;;;;;;;;;;;;;;;
;; Modules
;;;;;;;;;;;;;;;;;;;;;

[module/xworkspaces]
type = internal/xworkspaces

label-active = %icon%
label-occupied = %icon%
label-empty = %icon%

label-active-padding = 2
label-occupied-padding = 2
label-empty-padding = 2

label-active-foreground = #2E3440
label-active-background = ${colors.primary}

icon-0 = 1;%{T2}%{T-}
icon-1 = 2;%{T2}%{T-}
icon-2 = 3;%{T2}%{T-}
icon-3 = 4;%{T2}%{T-}
icon-4 = 5;%{T2}%{T-}
icon-5 = 6;%{T2}%{T-}

[module/xwindow]
type = internal/xwindow
label = %title%
label-maxlen = 50
label-foreground = ${colors.foreground}
label-empty = Desktop
label-empty-foreground = ${colors.secondary}


[module/pulseaudio]
type = internal/pulseaudio
format-volume = <label-volume>
label-volume = %{F#64B5F6}%{T2}%{T-}%{F-} %percentage%%
format-muted = <label-muted>
label-muted = %{F#64B5F6}%{T2}%{T-}%{F-} muted
use-ui-max = false
click-right = exec pavucontrol &

[module/memory]
type = internal/memory
interval = 2
warn-percentage = 90
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%
   

[module/cpu]
type = internal/cpu
interval = 2
format = <label>
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%
warn-percentage = 90


[module/powermenu]
type = custom/script
exec = echo $(whoami)
format-prefix-foreground = ${colors.primary}

[module/wlan]
type = internal/network
interface = wlan0
interface-type = wireless
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected = %{F#64B5F6}%{T1} %{F-}%{T0}%essid%
label-disconnected = %{F#B0BEC5}Disconnected%{F-}

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
poll-interval = 30
full-at = 100
low-at = 15

format-charging = ⚡ <ramp-capacity> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>
format-low = <ramp-capacity> <label-low>

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

ramp-capacity-0-foreground = #64B5F6
ramp-capacity-1-foreground = #64B5F6
ramp-capacity-2-foreground = #64B5F6
ramp-capacity-3-foreground = #64B5F6
ramp-capacity-4-foreground = #64B5F6

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = 100%
label-low = %percentage%%

 

[module/date]
type = internal/date
interval = 60
date = %Y-%m-%d %H:%M
format-prefix-foreground = ${colors.primary}
label = %date% 

