;==========================================================
; Polybar Config - Clean & Minimalist Nordic Style
;==========================================================
[colors]
background = #2E3440
background-alt = #3B4252
foreground = #D8DEE9
foreground-alt = #E5E9F0
primary = #81A1C1
secondary = #88C0D0
alert = #BF616A
disabled = #4C566A
border-clr = #00000000

[bar/bar]
width = 100%
height = 30
radius = 10
background = ${colors.background}
foreground = ${colors.foreground}
padding-left = 2 
padding-right = 2
module-margin = 1
font-0 = "JetBrainsMono Nerd Font:size=10;2"
font-1 = "Symbols Nerd Font Mono:size=12;2"
modules-left = xworkspaces 
modules-center = xwindow
modules-right = pulseaudio memory cpu powermenu wlan battery date
enable-ipc = true
monitor = ${env:MONITOR}

;;;;;;;;;;;;;;;;;;;;;
;; Modules
;;;;;;;;;;;;;;;;;;;;;

[module/xworkspaces]
type = internal/xworkspaces

label-active = %icon%
label-occupied = %icon%
label-empty = %icon%

label-active-padding = 2
label-occupied-padding = 2
label-empty-padding = 2

label-active-foreground = ${colors.primary}

label-active-underline = ${colors.primary}
label-active-overline = ${colors.primary}
icon-0 = 1;%{T2} %{T-}
icon-1 = 2;%{T2} %{T-}
icon-2 = 3;%{T2} %{T-}
icon-3 = 4;%{T2} %{T-}
icon-4 = 5;%{T2} %{T-}
icon-5 = 6;%{T2} %{T-}
icon-6 = 7;%{T2} %{T-}
icon-7 = 8;%{T2}󰙯 %{T-}

[module/xwindow]
type = internal/xwindow
label = %title%
label-maxlen = 50
label-foreground = ${colors.foreground}
label-empty = Desktop
label-empty-foreground = ${colors.secondary}


[module/pulseaudio]
type = internal/pulseaudio
format-volume = <label-volume>
label-volume = %{F#64B5F6}%{T2} %{T-}%{F-} %percentage%%
format-muted = <label-muted>
label-muted = %{F#64B5F6}%{T2}%{T-}%{F-} muted
use-ui-max = false
click-right = exec pavucontrol &

[module/memory]
type = internal/memory
interval = 2
warn-percentage = 90
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%
   

[module/cpu]
type = internal/cpu
interval = 2
format = <label>
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage: 2%%
warn-percentage = 90


[module/powermenu]
type = custom/script
exec = echo $(whoami)
format-prefix-foreground = ${colors.primary}

[module/wlan]
type = internal/network
interface-type = wireless
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected = %{F#64B5F6}%{T1}  %{F-}%{T0}%essid%
label-disconnected = %{F#B0BEC5}Disconnected%{F-}

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
poll-interval = 30
full-at = 100
low-at = 15

format-charging = %{F#A3BE8C}⚡ <ramp-capacity> <label-charging>%{F-}
format-discharging = <ramp-capacity> <label-discharging>
format-full = %{F#A3BE8C}<ramp-capacity> <label-full>%{F-}
format-low = %{F#BF616A}<ramp-capacity> <label-low>%{F-}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

ramp-capacity-0-foreground = #BF616A
ramp-capacity-1-foreground = #EBCB8B
ramp-capacity-2-foreground = #81A1C1
ramp-capacity-3-foreground = #81A1C1
ramp-capacity-4-foreground = #A3BE8C

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = 100%
label-low = %percentage%%
 

[module/date]
type = internal/date
interval = 60
date = %Y-%m-%d %H:%M
format-prefix-foreground = ${colors.primary}
label = %date% 

