# ==========================================================
# Hyprlock Config — Catppuccin Mocha 
# ==========================================================

background {
    monitor =
    path = /home/roviralta/.config/hypr/wallpaper.jpg  # Ruta de tu fondo
    blur_passes = 3                                 # Efecto desenfoque estilo Mac
    blur_size = 7
    noise = 0.0116
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.33 # Tamaño de los puntos de contraseña
    dots_spacing = 0.15 # Distancia entre puntos
    dots_center = true
    fade_on_empty = false
    
    # Colores Catppuccin Mocha
    outer_color = rgb(313244)
    inner_color = rgb(1e1e2e)
    font_color = rgb(cdd6f4)
    check_color = rgb(89b4fa)
    fail_color = rgb(f38ba8)
    
    placeholder_text = ***********
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}

# Reloj en pantalla de bloqueo
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(cdd6f4)
    font_size = 90
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 150
    halign = center
    valign = center
}
